/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as SitterTokenRouteRouteImport } from './routes/sitter/$token/route'
import { Route as SitterTokenIndexRouteImport } from './routes/sitter/$token/index'
import { Route as SitterTokenScanRouteImport } from './routes/sitter/$token/scan'
import { Route as SitterTokenGuideRouteImport } from './routes/sitter/$token/guide'
import { Route as SitterTokenEmergencyRouteImport } from './routes/sitter/$token/emergency'
import { Route as SitterTokenCareSheetRouteImport } from './routes/sitter/$token/care-sheet'
import { Route as AuthenticatedBirdsNewRouteImport } from './routes/_authenticated/birds/new'
import { Route as AuthenticatedBirdsBirdIdRouteImport } from './routes/_authenticated/birds/$birdId'
import { Route as AuthenticatedBirdsBirdIdIndexRouteImport } from './routes/_authenticated/birds/$birdId.index'
import { Route as AuthenticatedBirdsBirdIdSetupRouteImport } from './routes/_authenticated/birds/$birdId.setup'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SitterTokenRouteRoute = SitterTokenRouteRouteImport.update({
  id: '/sitter/$token',
  path: '/sitter/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SitterTokenIndexRoute = SitterTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SitterTokenRouteRoute,
} as any)
const SitterTokenScanRoute = SitterTokenScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => SitterTokenRouteRoute,
} as any)
const SitterTokenGuideRoute = SitterTokenGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => SitterTokenRouteRoute,
} as any)
const SitterTokenEmergencyRoute = SitterTokenEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => SitterTokenRouteRoute,
} as any)
const SitterTokenCareSheetRoute = SitterTokenCareSheetRouteImport.update({
  id: '/care-sheet',
  path: '/care-sheet',
  getParentRoute: () => SitterTokenRouteRoute,
} as any)
const AuthenticatedBirdsNewRoute = AuthenticatedBirdsNewRouteImport.update({
  id: '/birds/new',
  path: '/birds/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBirdsBirdIdRoute =
  AuthenticatedBirdsBirdIdRouteImport.update({
    id: '/birds/$birdId',
    path: '/birds/$birdId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBirdsBirdIdIndexRoute =
  AuthenticatedBirdsBirdIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBirdsBirdIdRoute,
  } as any)
const AuthenticatedBirdsBirdIdSetupRoute =
  AuthenticatedBirdsBirdIdSetupRouteImport.update({
    id: '/setup',
    path: '/setup',
    getParentRoute: () => AuthenticatedBirdsBirdIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/sitter/$token': typeof SitterTokenRouteRouteWithChildren
  '/account': typeof AuthenticatedAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/birds/$birdId': typeof AuthenticatedBirdsBirdIdRouteWithChildren
  '/birds/new': typeof AuthenticatedBirdsNewRoute
  '/sitter/$token/care-sheet': typeof SitterTokenCareSheetRoute
  '/sitter/$token/emergency': typeof SitterTokenEmergencyRoute
  '/sitter/$token/guide': typeof SitterTokenGuideRoute
  '/sitter/$token/scan': typeof SitterTokenScanRoute
  '/sitter/$token/': typeof SitterTokenIndexRoute
  '/birds/$birdId/setup': typeof AuthenticatedBirdsBirdIdSetupRoute
  '/birds/$birdId/': typeof AuthenticatedBirdsBirdIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/birds/new': typeof AuthenticatedBirdsNewRoute
  '/sitter/$token/care-sheet': typeof SitterTokenCareSheetRoute
  '/sitter/$token/emergency': typeof SitterTokenEmergencyRoute
  '/sitter/$token/guide': typeof SitterTokenGuideRoute
  '/sitter/$token/scan': typeof SitterTokenScanRoute
  '/sitter/$token': typeof SitterTokenIndexRoute
  '/birds/$birdId/setup': typeof AuthenticatedBirdsBirdIdSetupRoute
  '/birds/$birdId': typeof AuthenticatedBirdsBirdIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/sitter/$token': typeof SitterTokenRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/birds/$birdId': typeof AuthenticatedBirdsBirdIdRouteWithChildren
  '/_authenticated/birds/new': typeof AuthenticatedBirdsNewRoute
  '/sitter/$token/care-sheet': typeof SitterTokenCareSheetRoute
  '/sitter/$token/emergency': typeof SitterTokenEmergencyRoute
  '/sitter/$token/guide': typeof SitterTokenGuideRoute
  '/sitter/$token/scan': typeof SitterTokenScanRoute
  '/sitter/$token/': typeof SitterTokenIndexRoute
  '/_authenticated/birds/$birdId/setup': typeof AuthenticatedBirdsBirdIdSetupRoute
  '/_authenticated/birds/$birdId/': typeof AuthenticatedBirdsBirdIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/sitter/$token'
    | '/account'
    | '/dashboard'
    | '/notifications'
    | '/birds/$birdId'
    | '/birds/new'
    | '/sitter/$token/care-sheet'
    | '/sitter/$token/emergency'
    | '/sitter/$token/guide'
    | '/sitter/$token/scan'
    | '/sitter/$token/'
    | '/birds/$birdId/setup'
    | '/birds/$birdId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/account'
    | '/dashboard'
    | '/notifications'
    | '/birds/new'
    | '/sitter/$token/care-sheet'
    | '/sitter/$token/emergency'
    | '/sitter/$token/guide'
    | '/sitter/$token/scan'
    | '/sitter/$token'
    | '/birds/$birdId/setup'
    | '/birds/$birdId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/sitter/$token'
    | '/_authenticated/account'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/birds/$birdId'
    | '/_authenticated/birds/new'
    | '/sitter/$token/care-sheet'
    | '/sitter/$token/emergency'
    | '/sitter/$token/guide'
    | '/sitter/$token/scan'
    | '/sitter/$token/'
    | '/_authenticated/birds/$birdId/setup'
    | '/_authenticated/birds/$birdId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  SitterTokenRouteRoute: typeof SitterTokenRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/sitter/$token': {
      id: '/sitter/$token'
      path: '/sitter/$token'
      fullPath: '/sitter/$token'
      preLoaderRoute: typeof SitterTokenRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitter/$token/': {
      id: '/sitter/$token/'
      path: '/'
      fullPath: '/sitter/$token/'
      preLoaderRoute: typeof SitterTokenIndexRouteImport
      parentRoute: typeof SitterTokenRouteRoute
    }
    '/sitter/$token/scan': {
      id: '/sitter/$token/scan'
      path: '/scan'
      fullPath: '/sitter/$token/scan'
      preLoaderRoute: typeof SitterTokenScanRouteImport
      parentRoute: typeof SitterTokenRouteRoute
    }
    '/sitter/$token/guide': {
      id: '/sitter/$token/guide'
      path: '/guide'
      fullPath: '/sitter/$token/guide'
      preLoaderRoute: typeof SitterTokenGuideRouteImport
      parentRoute: typeof SitterTokenRouteRoute
    }
    '/sitter/$token/emergency': {
      id: '/sitter/$token/emergency'
      path: '/emergency'
      fullPath: '/sitter/$token/emergency'
      preLoaderRoute: typeof SitterTokenEmergencyRouteImport
      parentRoute: typeof SitterTokenRouteRoute
    }
    '/sitter/$token/care-sheet': {
      id: '/sitter/$token/care-sheet'
      path: '/care-sheet'
      fullPath: '/sitter/$token/care-sheet'
      preLoaderRoute: typeof SitterTokenCareSheetRouteImport
      parentRoute: typeof SitterTokenRouteRoute
    }
    '/_authenticated/birds/new': {
      id: '/_authenticated/birds/new'
      path: '/birds/new'
      fullPath: '/birds/new'
      preLoaderRoute: typeof AuthenticatedBirdsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/birds/$birdId': {
      id: '/_authenticated/birds/$birdId'
      path: '/birds/$birdId'
      fullPath: '/birds/$birdId'
      preLoaderRoute: typeof AuthenticatedBirdsBirdIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/birds/$birdId/': {
      id: '/_authenticated/birds/$birdId/'
      path: '/'
      fullPath: '/birds/$birdId/'
      preLoaderRoute: typeof AuthenticatedBirdsBirdIdIndexRouteImport
      parentRoute: typeof AuthenticatedBirdsBirdIdRoute
    }
    '/_authenticated/birds/$birdId/setup': {
      id: '/_authenticated/birds/$birdId/setup'
      path: '/setup'
      fullPath: '/birds/$birdId/setup'
      preLoaderRoute: typeof AuthenticatedBirdsBirdIdSetupRouteImport
      parentRoute: typeof AuthenticatedBirdsBirdIdRoute
    }
  }
}

interface AuthenticatedBirdsBirdIdRouteChildren {
  AuthenticatedBirdsBirdIdSetupRoute: typeof AuthenticatedBirdsBirdIdSetupRoute
  AuthenticatedBirdsBirdIdIndexRoute: typeof AuthenticatedBirdsBirdIdIndexRoute
}

const AuthenticatedBirdsBirdIdRouteChildren: AuthenticatedBirdsBirdIdRouteChildren =
  {
    AuthenticatedBirdsBirdIdSetupRoute: AuthenticatedBirdsBirdIdSetupRoute,
    AuthenticatedBirdsBirdIdIndexRoute: AuthenticatedBirdsBirdIdIndexRoute,
  }

const AuthenticatedBirdsBirdIdRouteWithChildren =
  AuthenticatedBirdsBirdIdRoute._addFileChildren(
    AuthenticatedBirdsBirdIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedBirdsBirdIdRoute: typeof AuthenticatedBirdsBirdIdRouteWithChildren
  AuthenticatedBirdsNewRoute: typeof AuthenticatedBirdsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedBirdsBirdIdRoute: AuthenticatedBirdsBirdIdRouteWithChildren,
  AuthenticatedBirdsNewRoute: AuthenticatedBirdsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SitterTokenRouteRouteChildren {
  SitterTokenCareSheetRoute: typeof SitterTokenCareSheetRoute
  SitterTokenEmergencyRoute: typeof SitterTokenEmergencyRoute
  SitterTokenGuideRoute: typeof SitterTokenGuideRoute
  SitterTokenScanRoute: typeof SitterTokenScanRoute
  SitterTokenIndexRoute: typeof SitterTokenIndexRoute
}

const SitterTokenRouteRouteChildren: SitterTokenRouteRouteChildren = {
  SitterTokenCareSheetRoute: SitterTokenCareSheetRoute,
  SitterTokenEmergencyRoute: SitterTokenEmergencyRoute,
  SitterTokenGuideRoute: SitterTokenGuideRoute,
  SitterTokenScanRoute: SitterTokenScanRoute,
  SitterTokenIndexRoute: SitterTokenIndexRoute,
}

const SitterTokenRouteRouteWithChildren =
  SitterTokenRouteRoute._addFileChildren(SitterTokenRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  SitterTokenRouteRoute: SitterTokenRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
