/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWelcomeRouteImport } from './routes/_authenticated/welcome'
import { Route as AuthenticatedSitsRouteImport } from './routes/_authenticated/sits'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedExploreRouteImport } from './routes/_authenticated/explore'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as SitterTokenRouteRouteImport } from './routes/sitter/$token/route'
import { Route as SitterTokenIndexRouteImport } from './routes/sitter/$token/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications.index'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account.index'
import { Route as SitterTokenScanRouteImport } from './routes/sitter/$token/scan'
import { Route as SitterTokenHomeRouteImport } from './routes/sitter/$token/home'
import { Route as SitterTokenGuideRouteImport } from './routes/sitter/$token/guide'
import { Route as SitterTokenEmergencyRouteImport } from './routes/sitter/$token/emergency'
import { Route as SitterTokenCareSheetRouteImport } from './routes/sitter/$token/care-sheet'
import { Route as AuthenticatedNotificationsSettingsRouteImport } from './routes/_authenticated/notifications.settings'
import { Route as AuthenticatedBirdsNewRouteImport } from './routes/_authenticated/birds/new'
import { Route as AuthenticatedBirdsBirdIdRouteImport } from './routes/_authenticated/birds/$birdId'
import { Route as AuthenticatedAccountSecurityRouteImport } from './routes/_authenticated/account.security'
import { Route as AuthenticatedBirdsBirdIdIndexRouteImport } from './routes/_authenticated/birds/$birdId.index'
import { Route as ApiPublicHooksCarePlanRemindersRouteImport } from './routes/api/public/hooks/care-plan-reminders'
import { Route as AuthenticatedBirdsBirdIdWeightRouteImport } from './routes/_authenticated/birds/$birdId.weight'
import { Route as AuthenticatedBirdsBirdIdVetSummaryRouteImport } from './routes/_authenticated/birds/$birdId.vet-summary'
import { Route as AuthenticatedBirdsBirdIdSetupRouteImport } from './routes/_authenticated/birds/$birdId.setup'
import { Route as AuthenticatedBirdsBirdIdPlanRouteImport } from './routes/_authenticated/birds/$birdId.plan'
import { Route as AuthenticatedBirdsBirdIdMomentsRouteImport } from './routes/_authenticated/birds/$birdId.moments'
import { Route as AuthenticatedBirdsBirdIdJournalRouteImport } from './routes/_authenticated/birds/$birdId.journal'
import { Route as AuthenticatedBirdsBirdIdIdentityRouteImport } from './routes/_authenticated/birds/$birdId.identity'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWelcomeRoute = AuthenticatedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSitsRoute = AuthenticatedSitsRouteImport.update({
  id: '/sits',
  path: '/sits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExploreRoute = AuthenticatedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SitterTokenRouteRoute = SitterTokenRouteRouteImport.update({
  id: '/sitter/$token',
  path: '/sitter/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SitterTokenIndexRoute = SitterTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SitterTokenRouteRoute,
} as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedNotificationsRoute,
  } as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const SitterTokenScanRoute = SitterTokenScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => SitterTokenRouteRoute,
} as any)
const SitterTokenHomeRoute = SitterTokenHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => SitterTokenRouteRoute,
} as any)
const SitterTokenGuideRoute = SitterTokenGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => SitterTokenRouteRoute,
} as any)
const SitterTokenEmergencyRoute = SitterTokenEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => SitterTokenRouteRoute,
} as any)
const SitterTokenCareSheetRoute = SitterTokenCareSheetRouteImport.update({
  id: '/care-sheet',
  path: '/care-sheet',
  getParentRoute: () => SitterTokenRouteRoute,
} as any)
const AuthenticatedNotificationsSettingsRoute =
  AuthenticatedNotificationsSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedNotificationsRoute,
  } as any)
const AuthenticatedBirdsNewRoute = AuthenticatedBirdsNewRouteImport.update({
  id: '/birds/new',
  path: '/birds/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBirdsBirdIdRoute =
  AuthenticatedBirdsBirdIdRouteImport.update({
    id: '/birds/$birdId',
    path: '/birds/$birdId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountSecurityRoute =
  AuthenticatedAccountSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedBirdsBirdIdIndexRoute =
  AuthenticatedBirdsBirdIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBirdsBirdIdRoute,
  } as any)
const ApiPublicHooksCarePlanRemindersRoute =
  ApiPublicHooksCarePlanRemindersRouteImport.update({
    id: '/api/public/hooks/care-plan-reminders',
    path: '/api/public/hooks/care-plan-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedBirdsBirdIdWeightRoute =
  AuthenticatedBirdsBirdIdWeightRouteImport.update({
    id: '/weight',
    path: '/weight',
    getParentRoute: () => AuthenticatedBirdsBirdIdRoute,
  } as any)
const AuthenticatedBirdsBirdIdVetSummaryRoute =
  AuthenticatedBirdsBirdIdVetSummaryRouteImport.update({
    id: '/vet-summary',
    path: '/vet-summary',
    getParentRoute: () => AuthenticatedBirdsBirdIdRoute,
  } as any)
const AuthenticatedBirdsBirdIdSetupRoute =
  AuthenticatedBirdsBirdIdSetupRouteImport.update({
    id: '/setup',
    path: '/setup',
    getParentRoute: () => AuthenticatedBirdsBirdIdRoute,
  } as any)
const AuthenticatedBirdsBirdIdPlanRoute =
  AuthenticatedBirdsBirdIdPlanRouteImport.update({
    id: '/plan',
    path: '/plan',
    getParentRoute: () => AuthenticatedBirdsBirdIdRoute,
  } as any)
const AuthenticatedBirdsBirdIdMomentsRoute =
  AuthenticatedBirdsBirdIdMomentsRouteImport.update({
    id: '/moments',
    path: '/moments',
    getParentRoute: () => AuthenticatedBirdsBirdIdRoute,
  } as any)
const AuthenticatedBirdsBirdIdJournalRoute =
  AuthenticatedBirdsBirdIdJournalRouteImport.update({
    id: '/journal',
    path: '/journal',
    getParentRoute: () => AuthenticatedBirdsBirdIdRoute,
  } as any)
const AuthenticatedBirdsBirdIdIdentityRoute =
  AuthenticatedBirdsBirdIdIdentityRouteImport.update({
    id: '/identity',
    path: '/identity',
    getParentRoute: () => AuthenticatedBirdsBirdIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/sitter/$token': typeof SitterTokenRouteRouteWithChildren
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/notifications': typeof AuthenticatedNotificationsRouteWithChildren
  '/sits': typeof AuthenticatedSitsRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/account/security': typeof AuthenticatedAccountSecurityRoute
  '/birds/$birdId': typeof AuthenticatedBirdsBirdIdRouteWithChildren
  '/birds/new': typeof AuthenticatedBirdsNewRoute
  '/notifications/settings': typeof AuthenticatedNotificationsSettingsRoute
  '/sitter/$token/care-sheet': typeof SitterTokenCareSheetRoute
  '/sitter/$token/emergency': typeof SitterTokenEmergencyRoute
  '/sitter/$token/guide': typeof SitterTokenGuideRoute
  '/sitter/$token/home': typeof SitterTokenHomeRoute
  '/sitter/$token/scan': typeof SitterTokenScanRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/sitter/$token/': typeof SitterTokenIndexRoute
  '/birds/$birdId/identity': typeof AuthenticatedBirdsBirdIdIdentityRoute
  '/birds/$birdId/journal': typeof AuthenticatedBirdsBirdIdJournalRoute
  '/birds/$birdId/moments': typeof AuthenticatedBirdsBirdIdMomentsRoute
  '/birds/$birdId/plan': typeof AuthenticatedBirdsBirdIdPlanRoute
  '/birds/$birdId/setup': typeof AuthenticatedBirdsBirdIdSetupRoute
  '/birds/$birdId/vet-summary': typeof AuthenticatedBirdsBirdIdVetSummaryRoute
  '/birds/$birdId/weight': typeof AuthenticatedBirdsBirdIdWeightRoute
  '/api/public/hooks/care-plan-reminders': typeof ApiPublicHooksCarePlanRemindersRoute
  '/birds/$birdId/': typeof AuthenticatedBirdsBirdIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/sits': typeof AuthenticatedSitsRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/account/security': typeof AuthenticatedAccountSecurityRoute
  '/birds/new': typeof AuthenticatedBirdsNewRoute
  '/notifications/settings': typeof AuthenticatedNotificationsSettingsRoute
  '/sitter/$token/care-sheet': typeof SitterTokenCareSheetRoute
  '/sitter/$token/emergency': typeof SitterTokenEmergencyRoute
  '/sitter/$token/guide': typeof SitterTokenGuideRoute
  '/sitter/$token/home': typeof SitterTokenHomeRoute
  '/sitter/$token/scan': typeof SitterTokenScanRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/sitter/$token': typeof SitterTokenIndexRoute
  '/birds/$birdId/identity': typeof AuthenticatedBirdsBirdIdIdentityRoute
  '/birds/$birdId/journal': typeof AuthenticatedBirdsBirdIdJournalRoute
  '/birds/$birdId/moments': typeof AuthenticatedBirdsBirdIdMomentsRoute
  '/birds/$birdId/plan': typeof AuthenticatedBirdsBirdIdPlanRoute
  '/birds/$birdId/setup': typeof AuthenticatedBirdsBirdIdSetupRoute
  '/birds/$birdId/vet-summary': typeof AuthenticatedBirdsBirdIdVetSummaryRoute
  '/birds/$birdId/weight': typeof AuthenticatedBirdsBirdIdWeightRoute
  '/api/public/hooks/care-plan-reminders': typeof ApiPublicHooksCarePlanRemindersRoute
  '/birds/$birdId': typeof AuthenticatedBirdsBirdIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/sitter/$token': typeof SitterTokenRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/explore': typeof AuthenticatedExploreRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRouteWithChildren
  '/_authenticated/sits': typeof AuthenticatedSitsRoute
  '/_authenticated/welcome': typeof AuthenticatedWelcomeRoute
  '/_authenticated/account/security': typeof AuthenticatedAccountSecurityRoute
  '/_authenticated/birds/$birdId': typeof AuthenticatedBirdsBirdIdRouteWithChildren
  '/_authenticated/birds/new': typeof AuthenticatedBirdsNewRoute
  '/_authenticated/notifications/settings': typeof AuthenticatedNotificationsSettingsRoute
  '/sitter/$token/care-sheet': typeof SitterTokenCareSheetRoute
  '/sitter/$token/emergency': typeof SitterTokenEmergencyRoute
  '/sitter/$token/guide': typeof SitterTokenGuideRoute
  '/sitter/$token/home': typeof SitterTokenHomeRoute
  '/sitter/$token/scan': typeof SitterTokenScanRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/sitter/$token/': typeof SitterTokenIndexRoute
  '/_authenticated/birds/$birdId/identity': typeof AuthenticatedBirdsBirdIdIdentityRoute
  '/_authenticated/birds/$birdId/journal': typeof AuthenticatedBirdsBirdIdJournalRoute
  '/_authenticated/birds/$birdId/moments': typeof AuthenticatedBirdsBirdIdMomentsRoute
  '/_authenticated/birds/$birdId/plan': typeof AuthenticatedBirdsBirdIdPlanRoute
  '/_authenticated/birds/$birdId/setup': typeof AuthenticatedBirdsBirdIdSetupRoute
  '/_authenticated/birds/$birdId/vet-summary': typeof AuthenticatedBirdsBirdIdVetSummaryRoute
  '/_authenticated/birds/$birdId/weight': typeof AuthenticatedBirdsBirdIdWeightRoute
  '/api/public/hooks/care-plan-reminders': typeof ApiPublicHooksCarePlanRemindersRoute
  '/_authenticated/birds/$birdId/': typeof AuthenticatedBirdsBirdIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/confirm-email'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/sitter/$token'
    | '/account'
    | '/dashboard'
    | '/explore'
    | '/notifications'
    | '/sits'
    | '/welcome'
    | '/account/security'
    | '/birds/$birdId'
    | '/birds/new'
    | '/notifications/settings'
    | '/sitter/$token/care-sheet'
    | '/sitter/$token/emergency'
    | '/sitter/$token/guide'
    | '/sitter/$token/home'
    | '/sitter/$token/scan'
    | '/account/'
    | '/notifications/'
    | '/sitter/$token/'
    | '/birds/$birdId/identity'
    | '/birds/$birdId/journal'
    | '/birds/$birdId/moments'
    | '/birds/$birdId/plan'
    | '/birds/$birdId/setup'
    | '/birds/$birdId/vet-summary'
    | '/birds/$birdId/weight'
    | '/api/public/hooks/care-plan-reminders'
    | '/birds/$birdId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/confirm-email'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/dashboard'
    | '/explore'
    | '/sits'
    | '/welcome'
    | '/account/security'
    | '/birds/new'
    | '/notifications/settings'
    | '/sitter/$token/care-sheet'
    | '/sitter/$token/emergency'
    | '/sitter/$token/guide'
    | '/sitter/$token/home'
    | '/sitter/$token/scan'
    | '/account'
    | '/notifications'
    | '/sitter/$token'
    | '/birds/$birdId/identity'
    | '/birds/$birdId/journal'
    | '/birds/$birdId/moments'
    | '/birds/$birdId/plan'
    | '/birds/$birdId/setup'
    | '/birds/$birdId/vet-summary'
    | '/birds/$birdId/weight'
    | '/api/public/hooks/care-plan-reminders'
    | '/birds/$birdId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/confirm-email'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/sitter/$token'
    | '/_authenticated/account'
    | '/_authenticated/dashboard'
    | '/_authenticated/explore'
    | '/_authenticated/notifications'
    | '/_authenticated/sits'
    | '/_authenticated/welcome'
    | '/_authenticated/account/security'
    | '/_authenticated/birds/$birdId'
    | '/_authenticated/birds/new'
    | '/_authenticated/notifications/settings'
    | '/sitter/$token/care-sheet'
    | '/sitter/$token/emergency'
    | '/sitter/$token/guide'
    | '/sitter/$token/home'
    | '/sitter/$token/scan'
    | '/_authenticated/account/'
    | '/_authenticated/notifications/'
    | '/sitter/$token/'
    | '/_authenticated/birds/$birdId/identity'
    | '/_authenticated/birds/$birdId/journal'
    | '/_authenticated/birds/$birdId/moments'
    | '/_authenticated/birds/$birdId/plan'
    | '/_authenticated/birds/$birdId/setup'
    | '/_authenticated/birds/$birdId/vet-summary'
    | '/_authenticated/birds/$birdId/weight'
    | '/api/public/hooks/care-plan-reminders'
    | '/_authenticated/birds/$birdId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  SitterTokenRouteRoute: typeof SitterTokenRouteRouteWithChildren
  ApiPublicHooksCarePlanRemindersRoute: typeof ApiPublicHooksCarePlanRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/welcome': {
      id: '/_authenticated/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthenticatedWelcomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sits': {
      id: '/_authenticated/sits'
      path: '/sits'
      fullPath: '/sits'
      preLoaderRoute: typeof AuthenticatedSitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/sitter/$token': {
      id: '/sitter/$token'
      path: '/sitter/$token'
      fullPath: '/sitter/$token'
      preLoaderRoute: typeof SitterTokenRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitter/$token/': {
      id: '/sitter/$token/'
      path: '/'
      fullPath: '/sitter/$token/'
      preLoaderRoute: typeof SitterTokenIndexRouteImport
      parentRoute: typeof SitterTokenRouteRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedNotificationsRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/sitter/$token/scan': {
      id: '/sitter/$token/scan'
      path: '/scan'
      fullPath: '/sitter/$token/scan'
      preLoaderRoute: typeof SitterTokenScanRouteImport
      parentRoute: typeof SitterTokenRouteRoute
    }
    '/sitter/$token/home': {
      id: '/sitter/$token/home'
      path: '/home'
      fullPath: '/sitter/$token/home'
      preLoaderRoute: typeof SitterTokenHomeRouteImport
      parentRoute: typeof SitterTokenRouteRoute
    }
    '/sitter/$token/guide': {
      id: '/sitter/$token/guide'
      path: '/guide'
      fullPath: '/sitter/$token/guide'
      preLoaderRoute: typeof SitterTokenGuideRouteImport
      parentRoute: typeof SitterTokenRouteRoute
    }
    '/sitter/$token/emergency': {
      id: '/sitter/$token/emergency'
      path: '/emergency'
      fullPath: '/sitter/$token/emergency'
      preLoaderRoute: typeof SitterTokenEmergencyRouteImport
      parentRoute: typeof SitterTokenRouteRoute
    }
    '/sitter/$token/care-sheet': {
      id: '/sitter/$token/care-sheet'
      path: '/care-sheet'
      fullPath: '/sitter/$token/care-sheet'
      preLoaderRoute: typeof SitterTokenCareSheetRouteImport
      parentRoute: typeof SitterTokenRouteRoute
    }
    '/_authenticated/notifications/settings': {
      id: '/_authenticated/notifications/settings'
      path: '/settings'
      fullPath: '/notifications/settings'
      preLoaderRoute: typeof AuthenticatedNotificationsSettingsRouteImport
      parentRoute: typeof AuthenticatedNotificationsRoute
    }
    '/_authenticated/birds/new': {
      id: '/_authenticated/birds/new'
      path: '/birds/new'
      fullPath: '/birds/new'
      preLoaderRoute: typeof AuthenticatedBirdsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/birds/$birdId': {
      id: '/_authenticated/birds/$birdId'
      path: '/birds/$birdId'
      fullPath: '/birds/$birdId'
      preLoaderRoute: typeof AuthenticatedBirdsBirdIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/security': {
      id: '/_authenticated/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AuthenticatedAccountSecurityRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/birds/$birdId/': {
      id: '/_authenticated/birds/$birdId/'
      path: '/'
      fullPath: '/birds/$birdId/'
      preLoaderRoute: typeof AuthenticatedBirdsBirdIdIndexRouteImport
      parentRoute: typeof AuthenticatedBirdsBirdIdRoute
    }
    '/api/public/hooks/care-plan-reminders': {
      id: '/api/public/hooks/care-plan-reminders'
      path: '/api/public/hooks/care-plan-reminders'
      fullPath: '/api/public/hooks/care-plan-reminders'
      preLoaderRoute: typeof ApiPublicHooksCarePlanRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/birds/$birdId/weight': {
      id: '/_authenticated/birds/$birdId/weight'
      path: '/weight'
      fullPath: '/birds/$birdId/weight'
      preLoaderRoute: typeof AuthenticatedBirdsBirdIdWeightRouteImport
      parentRoute: typeof AuthenticatedBirdsBirdIdRoute
    }
    '/_authenticated/birds/$birdId/vet-summary': {
      id: '/_authenticated/birds/$birdId/vet-summary'
      path: '/vet-summary'
      fullPath: '/birds/$birdId/vet-summary'
      preLoaderRoute: typeof AuthenticatedBirdsBirdIdVetSummaryRouteImport
      parentRoute: typeof AuthenticatedBirdsBirdIdRoute
    }
    '/_authenticated/birds/$birdId/setup': {
      id: '/_authenticated/birds/$birdId/setup'
      path: '/setup'
      fullPath: '/birds/$birdId/setup'
      preLoaderRoute: typeof AuthenticatedBirdsBirdIdSetupRouteImport
      parentRoute: typeof AuthenticatedBirdsBirdIdRoute
    }
    '/_authenticated/birds/$birdId/plan': {
      id: '/_authenticated/birds/$birdId/plan'
      path: '/plan'
      fullPath: '/birds/$birdId/plan'
      preLoaderRoute: typeof AuthenticatedBirdsBirdIdPlanRouteImport
      parentRoute: typeof AuthenticatedBirdsBirdIdRoute
    }
    '/_authenticated/birds/$birdId/moments': {
      id: '/_authenticated/birds/$birdId/moments'
      path: '/moments'
      fullPath: '/birds/$birdId/moments'
      preLoaderRoute: typeof AuthenticatedBirdsBirdIdMomentsRouteImport
      parentRoute: typeof AuthenticatedBirdsBirdIdRoute
    }
    '/_authenticated/birds/$birdId/journal': {
      id: '/_authenticated/birds/$birdId/journal'
      path: '/journal'
      fullPath: '/birds/$birdId/journal'
      preLoaderRoute: typeof AuthenticatedBirdsBirdIdJournalRouteImport
      parentRoute: typeof AuthenticatedBirdsBirdIdRoute
    }
    '/_authenticated/birds/$birdId/identity': {
      id: '/_authenticated/birds/$birdId/identity'
      path: '/identity'
      fullPath: '/birds/$birdId/identity'
      preLoaderRoute: typeof AuthenticatedBirdsBirdIdIdentityRouteImport
      parentRoute: typeof AuthenticatedBirdsBirdIdRoute
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountSecurityRoute: typeof AuthenticatedAccountSecurityRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountSecurityRoute: AuthenticatedAccountSecurityRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedNotificationsRouteChildren {
  AuthenticatedNotificationsSettingsRoute: typeof AuthenticatedNotificationsSettingsRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
}

const AuthenticatedNotificationsRouteChildren: AuthenticatedNotificationsRouteChildren =
  {
    AuthenticatedNotificationsSettingsRoute:
      AuthenticatedNotificationsSettingsRoute,
    AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  }

const AuthenticatedNotificationsRouteWithChildren =
  AuthenticatedNotificationsRoute._addFileChildren(
    AuthenticatedNotificationsRouteChildren,
  )

interface AuthenticatedBirdsBirdIdRouteChildren {
  AuthenticatedBirdsBirdIdIdentityRoute: typeof AuthenticatedBirdsBirdIdIdentityRoute
  AuthenticatedBirdsBirdIdJournalRoute: typeof AuthenticatedBirdsBirdIdJournalRoute
  AuthenticatedBirdsBirdIdMomentsRoute: typeof AuthenticatedBirdsBirdIdMomentsRoute
  AuthenticatedBirdsBirdIdPlanRoute: typeof AuthenticatedBirdsBirdIdPlanRoute
  AuthenticatedBirdsBirdIdSetupRoute: typeof AuthenticatedBirdsBirdIdSetupRoute
  AuthenticatedBirdsBirdIdVetSummaryRoute: typeof AuthenticatedBirdsBirdIdVetSummaryRoute
  AuthenticatedBirdsBirdIdWeightRoute: typeof AuthenticatedBirdsBirdIdWeightRoute
  AuthenticatedBirdsBirdIdIndexRoute: typeof AuthenticatedBirdsBirdIdIndexRoute
}

const AuthenticatedBirdsBirdIdRouteChildren: AuthenticatedBirdsBirdIdRouteChildren =
  {
    AuthenticatedBirdsBirdIdIdentityRoute:
      AuthenticatedBirdsBirdIdIdentityRoute,
    AuthenticatedBirdsBirdIdJournalRoute: AuthenticatedBirdsBirdIdJournalRoute,
    AuthenticatedBirdsBirdIdMomentsRoute: AuthenticatedBirdsBirdIdMomentsRoute,
    AuthenticatedBirdsBirdIdPlanRoute: AuthenticatedBirdsBirdIdPlanRoute,
    AuthenticatedBirdsBirdIdSetupRoute: AuthenticatedBirdsBirdIdSetupRoute,
    AuthenticatedBirdsBirdIdVetSummaryRoute:
      AuthenticatedBirdsBirdIdVetSummaryRoute,
    AuthenticatedBirdsBirdIdWeightRoute: AuthenticatedBirdsBirdIdWeightRoute,
    AuthenticatedBirdsBirdIdIndexRoute: AuthenticatedBirdsBirdIdIndexRoute,
  }

const AuthenticatedBirdsBirdIdRouteWithChildren =
  AuthenticatedBirdsBirdIdRoute._addFileChildren(
    AuthenticatedBirdsBirdIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExploreRoute: typeof AuthenticatedExploreRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRouteWithChildren
  AuthenticatedSitsRoute: typeof AuthenticatedSitsRoute
  AuthenticatedWelcomeRoute: typeof AuthenticatedWelcomeRoute
  AuthenticatedBirdsBirdIdRoute: typeof AuthenticatedBirdsBirdIdRouteWithChildren
  AuthenticatedBirdsNewRoute: typeof AuthenticatedBirdsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExploreRoute: AuthenticatedExploreRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRouteWithChildren,
  AuthenticatedSitsRoute: AuthenticatedSitsRoute,
  AuthenticatedWelcomeRoute: AuthenticatedWelcomeRoute,
  AuthenticatedBirdsBirdIdRoute: AuthenticatedBirdsBirdIdRouteWithChildren,
  AuthenticatedBirdsNewRoute: AuthenticatedBirdsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SitterTokenRouteRouteChildren {
  SitterTokenCareSheetRoute: typeof SitterTokenCareSheetRoute
  SitterTokenEmergencyRoute: typeof SitterTokenEmergencyRoute
  SitterTokenGuideRoute: typeof SitterTokenGuideRoute
  SitterTokenHomeRoute: typeof SitterTokenHomeRoute
  SitterTokenScanRoute: typeof SitterTokenScanRoute
  SitterTokenIndexRoute: typeof SitterTokenIndexRoute
}

const SitterTokenRouteRouteChildren: SitterTokenRouteRouteChildren = {
  SitterTokenCareSheetRoute: SitterTokenCareSheetRoute,
  SitterTokenEmergencyRoute: SitterTokenEmergencyRoute,
  SitterTokenGuideRoute: SitterTokenGuideRoute,
  SitterTokenHomeRoute: SitterTokenHomeRoute,
  SitterTokenScanRoute: SitterTokenScanRoute,
  SitterTokenIndexRoute: SitterTokenIndexRoute,
}

const SitterTokenRouteRouteWithChildren =
  SitterTokenRouteRoute._addFileChildren(SitterTokenRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConfirmEmailRoute: ConfirmEmailRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  SitterTokenRouteRoute: SitterTokenRouteRouteWithChildren,
  ApiPublicHooksCarePlanRemindersRoute: ApiPublicHooksCarePlanRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
