DELETE FROM public.guide_cards;

INSERT INTO public.guide_cards
  (slug, title, category, quick_answer, what_to_check, what_to_do, when_to_call_vet, emergency_level, search_keywords, reviewed_by, reviewed_at)
VALUES
('rule-dont-wait-and-see','Don''t wait and see','01-the-10-rules','Birds hide illness. By the time a parrot looks obviously sick, it can already be urgent.',NULL,'If something seems off, call the owner and the avian vet early. You will never be in trouble for calling too soon.','Any combination of fluffed, quiet, eating less, abnormal droppings, or breathing changes.','yellow','prey animal hides sickness late stage','The Kya Project · Parrot Care Bible',now()),
('rule-no-nonstick','No nonstick cookware','01-the-10-rules','Overheated PTFE / Teflon coatings release invisible, odorless fumes that kill birds within minutes.','Nonstick pans, air fryers, waffle makers, popcorn poppers, bread machines, slow cookers, rice cookers, oven drip pans, self-cleaning ovens, irons, hair dryers, heat lamps.','Do not use any nonstick or coated heated appliance while the bird is in the home.','Any open-mouth breathing, wheezing, collapse, or sudden death after suspected fume exposure — call immediately.','red','teflon ptfe fumes kitchen','The Kya Project · Parrot Care Bible',now()),
('rule-clean-air','No candles, aerosols, smoke, oils, or strong cleaners','01-the-10-rules','A bird''s respiratory system is extremely sensitive. If it is scented, sprayed, smoky, chemical, or heated — keep it away from the bird.','Candles, wax warmers, plug-ins, incense, essential-oil and reed diffusers, hairspray, perfume, sunscreen spray, air fresheners, cleaning sprays, insecticide, bleach, ammonia, paint, nail polish, smoke (cigarette, cannabis, wood, burnt food).','Apply any cleaner to a cloth in another room and wipe — never spray near the bird. Ventilate but avoid drafts.','Any breathing changes after exposure — call immediately.','red','air quality fumes aerosol candle essential oil','The Kya Project · Parrot Care Bible',now()),
('rule-doors-windows','Keep doors and windows closed','01-the-10-rules','Even clipped birds fly farther than people expect. A clipped bird can still flutter or be carried by wind.',NULL,'Close all windows and doors before opening the cage. Never open the front door while the bird is loose. Turn off ceiling fans.',NULL,'normal','escape flighted clipped','The Kya Project · Parrot Care Bible',now()),
('rule-supervise','Never leave the bird out unsupervised','01-the-10-rules','Most accidents happen during unsupervised out-of-cage time.',NULL,'If you cannot watch the bird, it goes back in the cage. No exceptions.',NULL,'normal','out of cage supervision','The Kya Project · Parrot Care Bible',now()),
('rule-owner-approved-food','Feed only what the owner approved','01-the-10-rules','Some common human foods are toxic. A sudden diet change can also upset the bird and make illness harder to spot.','The owner''s care sheet food list.','Stick to it. Do not introduce new foods, supplements, or treats while the owner is away.',NULL,'normal','diet feeding rules','The Kya Project · Parrot Care Bible',now()),
('rule-dont-force-handling','Don''t force handling','01-the-10-rules','You do not need to hold the bird to care for it well. For many parrots, calm cage-only company is the kindest care.',NULL,'Follow the owner''s handling rules exactly. Never chase the bird to make it step up.',NULL,'normal','handling trust shy','The Kya Project · Parrot Care Bible',now()),
('rule-daily-scan','Watch eating, droppings, breathing, posture, energy','01-the-10-rules','These five things are your best daily clues to whether the bird is well.','Look, listen, food, water, droppings, compare to owner notes.','Run the daily health scan every day. Photograph anything unusual before cleaning.',NULL,'normal','daily check scan baseline','The Kya Project · Parrot Care Bible',now()),
('rule-other-pets','Keep other pets away','01-the-10-rules','A cat or dog bite or scratch is ALWAYS an emergency, even if it looks tiny — bacteria can kill a bird within hours.',NULL,'Separate the bird from any other pet at all times. Even a friendly dog or cat is a risk.','Any contact between a cat/dog and the bird, even with no visible wound — call immediately.','red','cat dog bite scratch pasteurella','The Kya Project · Parrot Care Bible',now()),
('rule-emergency','In an emergency','01-the-10-rules','Stay calm. Keep the bird warm and quiet. Call the avian vet. Transport if needed.',NULL,'1) Stay calm. 2) Warmth — about 85–90°F if sick or shocky, heat on one side only. 3) Quiet, dim, minimally handled. 4) Call the avian vet and prepare to transport.','Always — when in doubt, call.','red','first aid four rules','The Kya Project · Parrot Care Bible',now()),

('scan-look','1. Look (before you interact)','02-the-daily-health-scan','Alert and aware of the room, perched normally, feathers smooth, eyes bright, breathing quiet, tail still at rest, moving normally.','Sitting higher or lower than usual? Fluffed? Tail bobbing with each breath? Both feet in use?','Take a mental photo before you make noise. Compare to the owner''s notes on what is normal for this bird.',NULL,'normal','observation posture','The Kya Project · Parrot Care Bible',now()),
('scan-listen','2. Listen','02-the-daily-health-scan','Normal sounds and pattern for this bird.','Much quieter than usual? Voice different? Wheezing, clicking, or raspy breathing? Sudden frantic calling?','Quiet birds are sometimes sick birds. Compare to baseline.','Wheezing, clicking, or raspy breathing — call immediately.','yellow','vocal quiet wheezing','The Kya Project · Parrot Care Bible',now()),
('scan-food','3. Check food','02-the-daily-health-scan','Don''t assume the bird is eating just because food is in the bowl.','Hulls in seed? Pellets actually reduced? Favorite foods ignored? Food picked up and dropped?','Note rough amounts eaten each day so a drop in appetite is obvious.','A bird that is not eating needs same-day attention.','yellow','appetite eating less','The Kya Project · Parrot Care Bible',now()),
('scan-water','4. Check water','02-the-daily-health-scan','Fresh, clean water daily. Watch for big changes either way.','Dirty? Drinking much more or less than usual? Dunking food?','Replace water daily (more if dirty). Do not add vitamins, supplements, or meds unless instructed.','A big sudden change in drinking — tell the owner; call the vet if combined with other signs.','normal','hydration water bowl','The Kya Project · Parrot Care Bible',now()),
('scan-droppings','5. Check droppings','02-the-daily-health-scan','Check before cleaning the cage paper. Three parts: feces, white urates, clear urine.','Normal number and size? Three parts visible? Blood? Black/tarry? Yellow or green urates? Undigested food? Foul smell?','Photograph anything unusual in good light with a coin for scale, before you clean.','Blood, black/tarry, no droppings, or droppings abnormal for ~24 hours — call.','yellow','poop stool feces urates','The Kya Project · Parrot Care Bible',now()),
('scan-compare','6. Compare to the owner''s notes','02-the-daily-health-scan','A change from normal is usually the first clue. One odd thing is rarely urgent; two or more together matters more.','Combinations like quiet + eating less, fluffed + abnormal droppings, sleeping more + sitting low, tail bobbing + open-mouth breathing.','The owner''s care sheet is your comparison point.','Two or more changes together — call.','yellow','baseline normal comparison','The Kya Project · Parrot Care Bible',now()),

('early-signs','Early warning signs','03-healthy-vs-sick','These don''t always mean serious illness — they mean pay attention.','Eating less; ignoring favorites; sleeping more; sitting low; quiet; staying fluffed beyond a brief moment; weak grip; not stepping up; hiding; changed voice or breathing sound.','Call the owner. Watch closely and consider calling the avian vet.','If two or more early signs appear together, or any sign persists.','yellow','watch for early warning','The Kya Project · Parrot Care Bible',now()),
('same-day-signs','Same-day call signs','03-healthy-vs-sick','These warrant calling the avian vet the same day.','Eating much less or not at all; repeated vomiting; fluffed and quiet; sitting hunched; sleeping much more; abnormal droppings ~24h; blood in droppings; weakness; discharge around eyes or nares; face feathers wet or matted; breathing that looks or sounds different.','Call the avian vet today. Keep the bird warm, quiet, and minimally handled.','Today.','yellow','same day vet','The Kya Project · Parrot Care Bible',now()),
('emergency-signs','Emergency signs — call now','03-healthy-vs-sick','Do not wait to see if the bird improves.','Open-mouth breathing; tail bobbing at rest; wheezing/clicking/raspy breathing; collapse; seizure; unresponsive or hard to wake; bleeding that won''t stop quickly; cat or dog bite/scratch; suspected poisoning; fume or smoke exposure; sitting on the cage floor fluffed and weak; unable to perch; major fall; straining to pass an egg; not eating or drinking for an extended stretch.','Stay calm. Warm, quiet, dim. Call the avian vet now and prepare to transport.','Immediately.','red','call now emergency','The Kya Project · Parrot Care Bible',now()),
('fluffed-feathers','Fluffed feathers for long periods','03-healthy-vs-sick','Brief fluff-and-shake is normal. A long-held fluff can mean cold, stressed, or sick.','Fluffed AND quiet, eyes partly closed, sitting low, on the cage floor, not eating, abnormal droppings, tail bobbing.','Warm the room slightly, reduce stress, watch closely.','If fluff persists or combines with any other sign — call.','yellow','puffed up sick posture','The Kya Project · Parrot Care Bible',now()),
('tail-bobbing','Tail bobbing at rest','03-healthy-vs-sick','Tail pumping with each breath while the bird is at rest can signal breathing trouble.','Also check for open-mouth breathing, fluffing, low energy, wheezing, wings held away, leaning forward.','Stop handling. Keep calm and warm.','Always — call the avian vet immediately.','red','respiratory breathing distress','The Kya Project · Parrot Care Bible',now()),
('open-mouth-breathing','Open-mouth breathing','03-healthy-vs-sick','Urgent unless the bird was just active, hot, or frightened and recovers quickly.','Stretching neck to breathe, wheezing, raspy sounds, wings held away, tail bobbing, sitting low and weak.','Don''t handle more than necessary. Keep calm. Move to fresh air. No fans pointed at the bird.','If it doesn''t resolve in a minute or two at rest — call immediately.','red','panting beak open respiratory','The Kya Project · Parrot Care Bible',now()),
('vomiting-vs-regurgitation','Vomiting vs regurgitation','03-healthy-vs-sick','Regurgitation is normal bonding behavior. Vomiting is concerning.','Regurgitation: gentle head-bob, food brought up neatly, clean face, bird otherwise normal. Vomiting: forceful head-shaking, food flung, wet/sticky face feathers, weak or fluffed, repeated.','If unsure which it was, treat as vomiting.','Vomiting, repeated episodes, or matted face feathers — call the vet.','yellow','throwing up regurg sick','The Kya Project · Parrot Care Bible',now()),

('droppings-parts','The three parts of a normal dropping','04-droppings','Feces (solid, formed, green/brown/olive/tan), urates (chalky white-to-cream kidney waste), and urine (clear watery liquid).',NULL,'Check droppings every day before changing the cage paper.',NULL,'normal','poop anatomy normal','The Kya Project · Parrot Care Bible',now()),
('droppings-color-food','Food-related color changes','04-droppings','Color usually matches what the bird ate and should pass.','Greens → brighter green. Berries → red/purple/dark. Carrot/sweet potato → orange. Pellets → brown/tan/green. Watery fruit → more liquid. Beets → red/pink.','Note what was fed. A red tint after berries is usually harmless — but red that looks like fresh blood should be treated seriously.','If red persists with no berries, or you see true blood — call.','normal','color food poop','The Kya Project · Parrot Care Bible',now()),
('droppings-changes','Dropping changes that need attention','04-droppings','Look for changes in color, content, frequency, and smell.','Black or tarry feces (digested blood); bright red blood; yellow or green urates (liver); red/rusty urates (kidney); all liquid no solid; very small or no droppings; undigested seeds/food; strong foul smell; bubbles or mucus.','Photograph in good light with scale (coin/finger) before cleaning.','Any of these — same-day call. Blood, black/tarry, or no droppings — call immediately.','red','abnormal poop blood urates','The Kya Project · Parrot Care Bible',now()),
('droppings-24h-rule','The 24-hour rule','04-droppings','One odd dropping can happen — patterns matter more than one sample.',NULL,'If droppings look unusual once, photograph and keep watching.','Droppings stay abnormal for ~24 hours, you see blood, the bird is also quiet/fluffed/weak/not eating, droppings suddenly become much fewer or none, undigested food, foul smell — call.','yellow','rule pattern monitor','The Kya Project · Parrot Care Bible',now()),
('droppings-watery-vs-diarrhea','Watery droppings vs diarrhea','04-droppings','They are different. Both can matter if persistent.','More urine: feces still formed, extra clear liquid around it (drinking more, watery foods, stress, warmth). True diarrhea: the feces itself is loose, unformed, or pudding-like.','Note which one you''re seeing in your check-in.','Either, if it continues or the bird seems unwell.','yellow','diarrhea wet polyuria','The Kya Project · Parrot Care Bible',now()),

('body-language-cheatsheet','Body-language cheat sheet','05-body-language','Read the WHOLE bird, not one signal.','Smooth feathers + relaxed = calm. Beak grinding = sleepy/happy. Quick fluff-and-shake = resetting. One foot tucked = comfortable. Eye pinning = excited/agitated. Tail fanning = excited/overstimulated. Slicked feathers = scared. Leaning away = wants space. Beak open + leaning forward = bite warning. Lunging = move away. Long-held fluff = possible illness. Tail bobbing at rest = possible breathing issue.','When two or more signals say "stop" — give space immediately.',NULL,'normal','body language signals reading','The Kya Project · Parrot Care Bible',now()),
('bite-warning-ladder','The bite-warning ladder','05-body-language','A bird almost always warns before it bites.','1) Leaning or turning away, 2) eyes pinning, 3) head/neck feathers raising, 4) beak opening, 5) lunging, 6) biting.','Most sitter bites happen because someone missed steps 1–5. When in doubt, give the bird space.',NULL,'normal','bite warnings prevent','The Kya Project · Parrot Care Bible',now()),
('after-a-bite','After a bite','05-body-language','A bite is communication, not bad behavior. Don''t punish.',NULL,'Stay calm. Put the bird down or step away if safe. Don''t yell, hit, flick, or spray. Wash the wound. Tell the owner. Think through which warning signs you missed.','A bite to your face, eye area, or a deep puncture wound needs prompt medical attention — for YOU.','yellow','bitten wound first aid','The Kya Project · Parrot Care Bible',now()),

('cage-only-care','You don''t have to hold the bird','06-trust-and-handling','For many parrots, calm cage-only company is the kindest care.',NULL,'Follow the owner''s handling rules exactly. Calm, predictable presence earns trust faster than handling.',NULL,'normal','no handling cage only shy','The Kya Project · Parrot Care Bible',now()),
('how-trust-is-built','How trust is built','06-trust-and-handling','Boring and consistent is exactly what earns a parrot''s trust.',NULL,'Move slowly. Speak before entering. Approach from the front. Stay at or below the bird''s eye level. Let the bird come to you. Sit and read aloud or work quietly nearby.',NULL,'normal','trust building approach','The Kya Project · Parrot Care Bible',now()),
('shoulder-rule','The shoulder rule','06-trust-and-handling','Do not allow an unfamiliar bird on your shoulder.',NULL,'It''s close to your face, ears, and eyes — a startled bite there can be serious.',NULL,'normal','shoulder face eye safety','The Kya Project · Parrot Care Bible',now()),
('step-up','If step-up handling is allowed','06-trust-and-handling','Only if the owner has approved it and shown you how.',NULL,'1) Approach calmly. 2) Speak to the bird. 3) Offer a steady finger near the lower belly just above the legs. 4) Use the cue word (usually "step up"). 5) Let the bird choose. 6) If it leans away, fluffs, pins, or opens its beak — stop and try later. Never chase.',NULL,'normal','step up handling cue','The Kya Project · Parrot Care Bible',now()),
('wont-go-back-in','Bird won''t go back in the cage','06-trust-and-handling','Don''t chase. Slow it down.',NULL,'Try a favorite treat in the cage, calm voice, dim the room slightly, time, slow movement, the owner''s cue, or stepping away and letting the bird choose.','If the bird is loose and you can''t safely get it back, call the owner or backup person.','normal','cage return chase','The Kya Project · Parrot Care Bible',now()),

('foods-never-feed','Foods NEVER to feed','07-food-and-water','Avocado, chocolate/cocoa, caffeine, alcohol, onion/garlic/chives/leeks, salt, fatty/fried foods, sugary/junk foods, xylitol, fruit pits and apple seeds, rhubarb, raw or dried uncooked beans, mushrooms, unripe/green tomato, raw/green potato, persimmons, milk and heavy dairy, nutmeg and heavy spices, moldy food, old nuts.',NULL,'If you''re not sure, don''t feed it. The owner''s approved list always wins.','Suspected toxic ingestion — call the avian vet or ASPCA Poison Control (888) 426-4435 immediately.','red','toxic food avocado chocolate xylitol','The Kya Project · Parrot Care Bible',now()),
('usually-safe-foods','Usually safe — if owner-approved','07-food-and-water','Always defer to the owner''s list.',NULL,'Vegetables (broccoli, carrots, cooked sweet potato, peas, green beans, peppers incl. hot, leafy greens, squash, cucumber). Fruits (apple no seeds, banana, berries, melon, mango, pineapple, stone fruit pit-out). Grains (cooked quinoa, brown rice, oats, whole grain bread/pasta). Proteins (cooked beans, lentils, cooked egg, small plain yogurt, unsalted nuts). Herbs (basil, cilantro, parsley, dill, mint, oregano, thyme). Pellets if part of normal diet.',NULL,'normal','safe foods produce','The Kya Project · Parrot Care Bible',now()),
('fresh-food-water','Fresh food and water safety','07-food-and-water','Remove fresh or wet food after about 2 hours unless the owner says otherwise.',NULL,'Wash produce. Serve plain — no salt, oil, butter, dressing, sauce, or seasoning. Replace water daily (more if dirty). Wash the bowl as instructed. Watch for food-dunking. Do not add vitamins, supplements, or medication to water unless instructed.','If the bird drinks much more or less than normal — tell the owner.','normal','spoilage water bowl','The Kya Project · Parrot Care Bible',now()),
('not-eating','A bird that isn''t eating','07-food-and-water','A bird that isn''t eating is always concerning. Birds have small reserves.','Full bowl untouched, ignored favorite treats, fewer or smaller droppings, sitting near food without eating, picking up and dropping food.','Offer favorites. Warm the room slightly. Tell the owner.','Not eating for an extended stretch — call immediately.','red','appetite anorexia not eating','The Kya Project · Parrot Care Bible',now()),

('company-is-care','Company is care','08-enrichment','Calm presence counts — you don''t need to entertain the bird constantly.',NULL,'Say good morning. Talk to the bird. Sit nearby. Read aloud. Leave a radio or TV on if that''s the normal routine. Be predictable.',NULL,'normal','social isolation company','The Kya Project · Parrot Care Bible',now()),
('check-toys-daily','Check toys daily','08-enrichment','Daily toy check prevents serious injuries.','Frayed rope or loose threads (can wrap around toes/neck/beak); sharp pieces, broken plastic, loose bells; cheap metal clips; small swallowable parts.','Remove anything unsafe and tell the owner what you removed. Don''t introduce new toys unless the owner left them and said to use them.','If a toe, leg, or neck is caught — free the bird carefully and call the vet for any injury.','yellow','toys safety frayed metal','The Kya Project · Parrot Care Bible',now()),
('out-of-cage','Out-of-cage time','08-enrichment','Only let the bird out if the owner approved it. Never leave a bird out unattended.',NULL,'Before opening the cage: close windows and doors, turn off fans, put other pets away, cover large glass or mirrors if needed, remove unsafe foods and plants, turn off hot appliances, make sure you have time to supervise, know how the bird usually goes back in.',NULL,'normal','flight room safety','The Kya Project · Parrot Care Bible',now()),
('screaming-noise','Screaming and noise','08-enrichment','Parrots are loud. The goal isn''t silence — it''s knowing what kind of noise you''re hearing.','Flock calls (dawn/dusk, normal); attention screaming (calling for you); alarm calls (sudden frantic); boredom (repeated, no trigger); pain/fear (unusual, sharp, distressed).','Don''t reward every scream. Reward quiet moments. Never yell back, hit the cage, spray, or cover as punishment.','Unusual, sharp, distressed sounds — check immediately. Persistent alarm calls — check for danger.','normal','screaming noise vocal','The Kya Project · Parrot Care Bible',now()),

('kitchen-hazards','Kitchen hazards','09-the-safe-home','The kitchen is the most dangerous room.','Nonstick pans, pots, griddles, woks, air fryers, waffle makers, popcorn poppers, bread machines, slow cookers, rice cookers, oven drip pans, self-cleaning ovens, hot pans, boiling water, open trash, unsafe foods within reach.','No cooking while the bird is loose. No nonstick or coated heated appliance while the bird is in the home. Bird out of the kitchen during cooking.','Any breathing change after kitchen exposure — call immediately.','red','kitchen teflon air fryer','The Kya Project · Parrot Care Bible',now()),
('room-checklist','Room-by-room checklist','09-the-safe-home','A quick room scan prevents most accidents.','Open windows/doors, ceiling fans, glass/mirrors, open water (toilet, sink, tub, bucket, aquarium), open flames, hot surfaces, electrical cords, recliners, the bird underfoot, string/yarn/frayed rope, small swallowable objects.','Living room: fans off, doors/windows shut, blinds closed if bird may hit glass, no candles/diffusers, no recliners while bird is out. Bathroom: toilet lid down, no sprays/perfume/hot tools, no open meds. Bedroom: fan off, jewelry/meds away, drawers closed. Laundry: keep bird out entirely.',NULL,'yellow','room safety check','The Kya Project · Parrot Care Bible',now()),
('plants-wood','Plants, woods, and chewing hazards','09-the-safe-home','Don''t let the bird chew any plant, flower, branch, wood, or decoration unless the owner says it''s safe.','Common toxic plants: philodendron, pothos, dieffenbachia, ivy, peace/calla lily, lily-of-the-valley, poinsettia, holly, mistletoe, azalea, rhododendron, oleander, foxglove, daffodil, hyacinth, tulip & amaryllis bulbs, iris, caladium, elephant ear, sago palm, yew, boxwood, morning glory, hydrangea, wisteria, nightshade. Also avocado, apple, and cherry tree leaves/bark. Unsafe woods: cedar, redwood, some fir, oak, cherry, stone-fruit, yew, walnut, boxwood, holly, oleander.','Move the bird away from any unapproved plant or wood. Even "safe" plants may carry pesticide residue.','Suspected ingestion — call the avian vet or ASPCA Poison Control (888) 426-4435.','red','toxic plant wood chew','The Kya Project · Parrot Care Bible',now()),
('metals-poisons','Metals and poisons','09-the-safe-home','Lead and zinc are common, hidden poisons. Parrots explore with their beaks.','Lead: old/peeling paint, stained-glass solder, fishing/curtain weights, costume jewelry, leaded crystal, wine-bottle foil, antique toys, old linoleum, batteries. Zinc: galvanized wire, cheap cage clips, quick links, padlocks, keys, zippers, hardware, pennies. Also: pesticides, rodenticides, ant traps, antifreeze, human meds, cigarette butts, alcohol, caffeine, chocolate, glue/sticky traps.','Remove the bird from the substance. Do NOT make the bird vomit. Save or photograph packaging.','Suspected poisoning — call the avian vet or ASPCA Poison Control (888) 426-4435.','red','lead zinc metal poison','The Kya Project · Parrot Care Bible',now()),
('temperature','Temperature, drafts, and weather','09-the-safe-home','Most pet parrots are comfortable in the same temperatures people are, but sudden changes are stressful.','Too cold: fluffed a long time, quiet, shivering, feet tucked constantly, low energy. Too hot: wings held away from body, open-mouth breathing, panting, feathers slicked, seeking shade or water.','Keep away from drafty windows, AC/heating vents, direct sun with no shade, and space heaters unless owner-approved.','Trouble breathing is always urgent — call immediately.','yellow','temperature heat cold draft','The Kya Project · Parrot Care Bible',now()),

('first-aid-kit','The avian first-aid kit','10-emergencies','Ask the owner where it is BEFORE they leave.',NULL,'Typical contents: styptic powder or cornstarch; gauze pads, vet wrap, paper tape; cotton swabs, blunt tweezers or hemostat; small flashlight; towel; needleless syringe; bird-safe electrolyte solution; saline; small travel carrier; heat pack or hand warmer; vet phone numbers taped inside.',NULL,'normal','first aid kit supplies','The Kya Project · Parrot Care Bible',now()),
('transport-to-vet','How to transport a bird to the vet','10-emergencies','Warm, quiet, dark, secure.',NULL,'1) Small carrier or box lined with a towel — not loose bedding. 2) Warm — ~85–90°F using a wrapped warm water bottle or heat pack against ONE side only. 3) Cover the carrier. 4) Bring this guide, the owner''s care sheet, any medications, photos/samples of abnormal droppings, and anything the bird ate or chewed (with packaging). 5) Secure in the car, drive calmly, no blasting music or vents at the bird. 6) Call ahead.',NULL,'red','transport carrier vet','The Kya Project · Parrot Care Bible',now()),
('escaped-outside','If the bird gets out','10-emergencies','Act fast — don''t panic, don''t chase.',NULL,'Don''t take your eyes off the bird. Note exactly where it lands. Call to it with familiar words and its name. Bring the cage outside if safe with favorite food in view. Play recordings of the bird or familiar household sounds. Call the owner immediately. Search high (trees, roofs, poles) and wide. Walk, call, then pause and listen. Post in local lost-pet and bird groups; contact nearby vets, shelters, animal control, Parrot Alert.',NULL,'red','lost escaped flew outside','The Kya Project · Parrot Care Bible',now()),

('molting','Molting','11-special-situations','Replacing feathers: dropped feathers, spiky pin feathers, more preening, sometimes grumpy or itchy.',NULL,'Normal. Avoid touching pin feathers — they''re sensitive.','Bald patches, bleeding, or the bird seems unwell — call.','normal','molt pin feathers','The Kya Project · Parrot Care Bible',now()),
('egg-laying','Egg laying','11-special-situations','Females can lay without a mate.',NULL,'Tell the owner if you see an egg. Don''t remove eggs abruptly unless instructed.','Straining, weakness, sitting low, wide stance, tail bobbing, swollen lower belly, not passing droppings = possible egg binding — call the vet urgently.','red','egg laying binding female','The Kya Project · Parrot Care Bible',now()),
('hormonal','Hormonal behavior','11-special-situations','Territorial, nippy, loud, extra clingy, protective of cage/person/toy/dark space, interested in nesting spots.',NULL,'Give space. Avoid petting the back, wings, or tail. Avoid dark, nesty spaces. Keep the sleep routine consistent. Don''t force handling.',NULL,'normal','hormonal nesting territorial','The Kya Project · Parrot Care Bible',now()),
('night-frights','Night frights','11-special-situations','Some birds — especially cockatiels — panic in the dark and thrash, sometimes injuring themselves.',NULL,'If the owner uses a night light, keep it on. If you hear nighttime commotion: turn on a soft light, speak calmly, check for bleeding or injury, don''t grab unless necessary.','If the bird is hurt, weak, bleeding, or can''t perch — call.','yellow','night fright cockatiel thrash','The Kya Project · Parrot Care Bible',now()),
('feather-plucking','Feather-destructive behavior','11-special-situations','Some birds pluck or barber feathers.',NULL,'If the bird already does this, it''s not your fault. Keep the routine calm and note any changes. If it suddenly worsens, tell the owner.',NULL,'normal','plucking barbering feathers','The Kya Project · Parrot Care Bible',now()),

('check-ins','Check-ins with the owner','12-keeping-the-owner-informed','Follow the care sheet. If it doesn''t specify, ask before they leave; a short daily text is a good default.','Did the bird eat and drink? Droppings normal? Energy and behavior normal? Out-of-cage time? Anything unusual — even small things? Photo when you can.','For anything on the emergency list, call right away — don''t wait for the next scheduled check-in.',NULL,'normal','check in update owner','The Kya Project · Parrot Care Bible',now()),
('capture-useful','How to capture something useful','12-keeping-the-owner-informed','Good evidence helps the vet decide fast.',NULL,'Droppings: photograph the cage paper before cleaning, in good light, with a coin or finger for scale. Breathing: take a 5–10 second video of the bird at rest. Posture/behavior: a short video tells the story better than words. Note the time and what you observed.',NULL,'normal','photo video evidence','The Kya Project · Parrot Care Bible',now());